# - hosts: public-daemon,private-daemon,winning-post-miner,window-post-miner,seal-miner,precommit-worker,commit-worker
- hosts: all
  remote_user: '{{ remote_user }}'
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create prometheus run direction
      file:
        path: '/root/prometheus/run'
        state: directory

    - name: Copy node exporter script to remote server
      copy:
        src: '/home/omega/lotus-ops/scripts/install-node-exporter.sh'
        dest: '/root/workspace'
        owner: root
        group: root
        mode: +x

    - name: Copy node exporter service to remote server
      copy:
        src: '/home/omega/lotus-ops/service/node-exporter.service'
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: +x

    - name: Install node exporter
      shell: '/root/workspace/install-node-exporter.sh'
